APP_PORT = "8080"
CAMERA_PORT = "8082"
BASE_IMG_DIRECTORY = "/img"
RELATIVE_IMG_DIRECTORY = "/static" + BASE_IMG_DIRECTORY
SNAPSHOT_URL = "http://localhost:8081/0/action/snapshot"
MAX_GALLERY_SIZE = 20